shellEmulator: true
trustPolicy: no-downgrade

catalog:
  '@ai-sdk/cohere': ^3.0.18
  '@ai-sdk/google': ^3.0.20
  '@ai-sdk/mistral': ^3.0.18
  '@ai-sdk/openai': ^3.0.25
  '@antfu/eslint-config': ^7.2.0
  '@arethetypeswrong/cli': ^0.18.2
  '@cloudflare/workers-types': ^4.20260203.0
  '@huggingface/transformers': ^3.8.1
  '@libsql/client': ^0.17.0
  '@types/node': ^25.2.0
  '@types/pg': ^8.16.0
  '@upstash/vector': ^1.2.2
  '@vitest/coverage-v8': ^4.0.18
  ai: ^6.0.69
  ai-sdk-provider-gemini-cli: ^2.0.1
  bumpp: ^10.4.0
  eslint: ^9.39.2
  obuild: ^0.4.22
  osgrep: ^0.5.16
  pg: ^8.18.0
  sqlite-vec: ^0.1.7-alpha.2
  typescript: ^5.9.3
  vitest: ^4.0.18
  zod: ^4.3.6
ignoredBuiltDependencies:
  - better-sqlite3
  - esbuild
