catalog:
  '@antfu/eslint-config': ^6.7.3
  '@arethetypeswrong/cli': ^0.18.2
  '@libsql/client': ^0.17.0
  '@types/better-sqlite3': ^7.6.13
  '@types/node': ^22.10.0
  '@upstash/vector': ^1.1.0
  ai: ^4.3.0
  better-sqlite3: ^12.5.0
  eslint: ^9.39.2
  obuild: ^0.4.14
  typescript: ^5.9.3
  vitest: ^4.0.16
