shellEmulator: true

trustPolicy: no-downgrade

catalog:
  '@ai-sdk/cohere': ^3.0.27
  '@ai-sdk/google': ^3.0.53
  '@ai-sdk/mistral': ^3.0.27
  '@ai-sdk/openai': ^3.0.48
  '@antfu/eslint-config': ^7.7.3
  '@arethetypeswrong/cli': ^0.18.2
  '@cloudflare/workers-types': ^4.20260329.1
  '@huggingface/transformers': ^3.8.1
  '@libsql/client': ^0.17.2
  '@types/node': ^25.5.0
  '@types/pg': ^8.20.0
  '@upstash/vector': ^1.2.3
  '@vitest/coverage-v8': ^4.1.2
  ai: ^6.0.141
  ai-sdk-provider-gemini-cli: ^2.0.1
  bumpp: ^11.0.1
  eslint: ^10.1.0
  obuild: ^0.4.32
  osgrep: ^0.5.16
  pg: ^8.20.0
  sqlite-vec: ^0.1.8
  typescript: ^6.0.2
  vitest: ^4.1.2
  zod: ^4.3.6
ignoredBuiltDependencies:
  - better-sqlite3
  - esbuild
